CREATE DATABASE SENAI_CZBOOKS_MANHA;

USE SENAI_CZBOOKS_MANHA;

CREATE TABLE Biblioteca(
IdInstituicao INT PRIMARY KEY IDENTITY
,NomeBiblioteca VARCHAR (200) NOT NULL
, CNPJ  varchar (200)
,Endereco VARCHAR (200)
);

CREATE TABLE Livros
(
IdLivro INT PRIMARY KEY IDENTITY
,IdAutor INT FOREIGN KEY  REFERENCES Autor(IdAutor)
,IdCategoria INT FOREIGN KEY  REFERENCES Categoria(IdCategoria)
,IdBiblioteca INT FOREIGN KEY  REFERENCES Biblioteca(IdBiblioteca)
,Titulo VARCHAR (100) NOT NULL
,Sinopse VARCHAR (200)
, Preco FLOAT
, DataPublicacao VARCHAR (200)
);


CREATE TABLE Categoria
(
IdCategoria INT PRIMARY KEY IDENTITY
,IdLivros INT FOREIGN KEY REFERENCES Livros(IdLivros)
,NomeCategoria VARCHAR(100) NOT NULL
);


CREATE TABLE Usuario
(
IdUsuario INT PRIMARY KEY IDENTITY
,IdAcesso INT FOREIGN KEY REFERENCES Acesso(IdAcesso)
,NomeUsuario VARCHAR(200) NOT NULL
,DataAtualizacao VARCHAR(200) NOT NULL
,DataCriacao VARCHAR(300) NOT NULL
);

CREATE TABLE Autor
(
IdUsuarios INT PRIMARY KEY IDENTITY
IdAutor INT PRIMARY KEY IDENTITY
,IdUsuario INT FOREIGN KEY  REFERENCES Usuario(IdUsuario)
,Idade INT 
);



CREATE TABLE Administrador
(
IdUsuarios INT PRIMARY KEY IDENTITY
,IdAcesso INT FOREIGN KEY REFERENCES Acesso(IdAcesso)
,NomeADM VARCHAR(200) NOT NULL
,DataCriacao VARCHAR(300) NOT NULL
);
